# Generated by Django 3.2.2 on 2021-05-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='excursions.excursion', verbose_name='Экскурсия'),
        ),
    ]
