# Generated by Django 3.2.2 on 2021-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_auto_20210510_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала экскурсии'),
        ),
    ]
