# Generated by Django 3.2.2 on 2021-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_alter_excursion_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='max_people_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во человек'),
        ),
    ]
