# Generated by Django 3.2.3 on 2021-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_alter_photo_excursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически', max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
