# Generated by Django 3.2.2 on 2021-05-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_alter_excursion_max_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
    ]
