# Generated by Django 3.2.2 on 2021-05-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0005_alter_excursion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Фото', max_length=100, verbose_name='Подпись фото'),
        ),
    ]
