# Generated by Django 3.2.2 on 2021-05-10 19:26

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0006_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=smartfields.fields.ImageField(null=True, upload_to='excursions_photos', verbose_name='Фото'),
        ),
    ]
