# Generated by Django 3.2.2 on 2021-05-10 19:35

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_small',
            field=smartfields.fields.ImageField(null=True, upload_to='excursions_photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=smartfields.fields.ImageField(null=True, upload_to='excursions_photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Фото', max_length=100, verbose_name='Подпись к фото'),
        ),
    ]
