# Generated by Django 3.2.2 on 2021-05-10 19:37

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0008_auto_20210510_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='excursions_photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='excursions_photos'),
        ),
    ]
