# Generated by Django 3.2.2 on 2021-05-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0010_auto_20210510_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='excursions_photos/None', verbose_name='Фото'),
        ),
    ]
